# Generated by Django 2.2.4 on 2020-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledemo',
            name='organization',
            field=models.CharField(blank=True, max_length=24, verbose_name='拥有我'),
        ),
    ]
